  snowball-explosion-power: 1.1
  snowball-give-interval: 200
  explosion-power-ratio: 2

  map:
    map-top-vertex-ordinate: 150
    map-bottom-vertex-ordinate: 150
    map-radius: 50
    map-origin-point:
      x: 1000
      y: 100
      z: 1000